[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
koin-bom = "4.1.1"
amplitude = "1.22.4"
appodeal = "3.11.0.0"
google-review = "2.0.2"
google-play-services-ads = "24.8.0"
firebase-bom = "34.6.0"
coroutines = "1.10.2"
billing-ktx = "8.1.0"
okhttp3 = "5.3.2"
retrofit2 = "3.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android" }
amplitude = { module = "com.amplitude:analytics-android", version.ref = "amplitude" }
appodeal = { module = "com.appodeal.ads:sdk", version.ref = "appodeal" }

google-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "google-review" }
google-play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "google-play-services-ads" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

billingclient = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }

squareup-okhttp3-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
squareup-okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
squareup-retrofit2-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
squareup-retrofit2-converters-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
