[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
koin-bom = "4.1.1"
amplitude = "1.22.4"
appodeal = "3.10.0.0"
google-review = "2.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-android = { module = "io.insert-koin:koin-android" }
amplitude = { module = "com.amplitude:analytics-android", version.ref = "amplitude" }
appodeal = { module = "com.appodeal.ads:sdk", version.ref = "appodeal" }
google-review = { module = "com.google.android.play:review", version.ref = "google-review" }
google-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "google-review" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

